apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic/.devcontainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-container
          image: pnc21/spring-petclinic/.devcontainer:latest
          ports:
            - containerPort: 8080
