apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer isn't supported
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 8080
